aliases: []
creation_timestamp: 1757959983570
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1757959983570
metrics: null
model_id: m-ecb400c1690846208b3484a73e934bc0
name: StockModel
params: null
run_id: c893c10d94334af580d419bc1070ed40
run_link: null
source: models:/m-ecb400c1690846208b3484a73e934bc0
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/models/m-ecb400c1690846208b3484a73e934bc0/artifacts
user_id: null
version: 1
