aliases: []
creation_timestamp: 1758301826135
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1758301826135
metrics: null
model_id: m-72bbfc04bc7b4dbf8ede2c2a526d83a5
name: StockModel
params: null
run_id: f94e47bc97ec4275b31c034cd8e6d079
run_link: null
source: models:/m-72bbfc04bc7b4dbf8ede2c2a526d83a5
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/446092070879665876/models/m-72bbfc04bc7b4dbf8ede2c2a526d83a5/artifacts
user_id: null
version: 1
