artifact_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/real_state/mlflow/944774172628594434
creation_time: 1758308148003
experiment_id: '944774172628594434'
last_update_time: 1758308148003
lifecycle_stage: active
name: real_state_experiment
