artifact_uri: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/d8decd280c5d49f5921aa49bdec3b479/artifacts
end_time: 1757960899690
entry_point_name: ''
experiment_id: '696107119862965157'
lifecycle_stage: active
run_id: d8decd280c5d49f5921aa49bdec3b479
run_name: stock_model_demo
source_name: ''
source_type: 4
source_version: ''
start_time: 1757960896558
status: 3
tags: []
user_id: Admin
