artifact_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/real_state/mlflow/0
creation_time: 1758308147984
experiment_id: '0'
last_update_time: 1758308147984
lifecycle_stage: active
name: Default
