aliases: []
creation_timestamp: 1757961128164
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1757961128164
metrics: null
model_id: m-cf5512162bd44829be81c392e93e2ce0
name: StockModel
params: null
run_id: 2e75568218444e3e9d019e08669e7135
run_link: null
source: models:/m-cf5512162bd44829be81c392e93e2ce0
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/models/m-cf5512162bd44829be81c392e93e2ce0/artifacts
user_id: null
version: 8
