artifact_uri: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/c893c10d94334af580d419bc1070ed40/artifacts
end_time: 1757959983495
entry_point_name: ''
experiment_id: '696107119862965157'
lifecycle_stage: active
run_id: c893c10d94334af580d419bc1070ed40
run_name: stock_model_demo
source_name: ''
source_type: 4
source_version: ''
start_time: 1757959980038
status: 3
tags: []
user_id: Admin
