artifact_uri: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/daa41bff1103473db1f8ccffc4ae3823/artifacts
end_time: 1757960710517
entry_point_name: ''
experiment_id: '696107119862965157'
lifecycle_stage: active
run_id: daa41bff1103473db1f8ccffc4ae3823
run_name: stock_model_demo
source_name: ''
source_type: 4
source_version: ''
start_time: 1757960707650
status: 3
tags: []
user_id: Admin
