aliases: []
creation_timestamp: 1757960122007
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1757960122007
metrics: null
model_id: m-f30f8e0a74974833ac6d653150cb4a2d
name: StockModel
params: null
run_id: bc55045b09564312ba9d9d6369d0b0a2
run_link: null
source: models:/m-f30f8e0a74974833ac6d653150cb4a2d
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/models/m-f30f8e0a74974833ac6d653150cb4a2d/artifacts
user_id: null
version: 3
