artifact_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/0
creation_time: 1758301821729
experiment_id: '0'
last_update_time: 1758301821729
lifecycle_stage: active
name: Default
