aliases: []
creation_timestamp: 1757960788350
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1757960788350
metrics: null
model_id: m-2ba624835c224422888f5befaf11e6a0
name: StockModel
params: null
run_id: daa41bff1103473db1f8ccffc4ae3823
run_link: null
source: models:/m-2ba624835c224422888f5befaf11e6a0
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/models/m-2ba624835c224422888f5befaf11e6a0/artifacts
user_id: null
version: 6
