artifact_uri: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/9181122d3acf40e4a471b8be186f8bd3/artifacts
end_time: 1757960641594
entry_point_name: ''
experiment_id: '696107119862965157'
lifecycle_stage: active
run_id: 9181122d3acf40e4a471b8be186f8bd3
run_name: stock_model_demo
source_name: ''
source_type: 4
source_version: ''
start_time: 1757960638707
status: 3
tags: []
user_id: Admin
