aliases: []
creation_timestamp: 1758308323620
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1758308323620
metrics: null
model_id: m-958126b2b1f64a6a9b042d4870ef87c6
name: RealStateModel
params: null
run_id: d831dcf83826454d841d41bc0d401950
run_link: null
source: models:/m-958126b2b1f64a6a9b042d4870ef87c6
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/real_state/mlflow/944774172628594434/models/m-958126b2b1f64a6a9b042d4870ef87c6/artifacts
user_id: null
version: 1
