aliases: []
creation_timestamp: 1757961057276
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1757961057276
metrics: null
model_id: m-1543ff5a7b574a3986f1dcabe32d5770
name: StockModel
params: null
run_id: d8decd280c5d49f5921aa49bdec3b479
run_link: null
source: models:/m-1543ff5a7b574a3986f1dcabe32d5770
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/models/m-1543ff5a7b574a3986f1dcabe32d5770/artifacts
user_id: null
version: 7
