aliases: []
creation_timestamp: 1757960650720
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1757960650720
metrics: null
model_id: m-cb816e424c3e45c09a74fdf823feea0f
name: StockModel
params: null
run_id: 9181122d3acf40e4a471b8be186f8bd3
run_link: null
source: models:/m-cb816e424c3e45c09a74fdf823feea0f
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157/models/m-cb816e424c3e45c09a74fdf823feea0f/artifacts
user_id: null
version: 4
