artifact_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/696107119862965157
creation_time: 1757959979866
experiment_id: '696107119862965157'
last_update_time: 1757959979866
lifecycle_stage: active
name: stock_experiment
