artifact_location: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/446092070879665876
creation_time: 1758301821747
experiment_id: '446092070879665876'
last_update_time: 1758301821747
lifecycle_stage: active
name: stock_experiment
