artifact_uri: file:///C:/Users/Admin/Documents/DataScience/DataOps/MLOps/modeling/stock_model/mlflow/446092070879665876/f94e47bc97ec4275b31c034cd8e6d079/artifacts
end_time: 1758301826048
entry_point_name: ''
experiment_id: '446092070879665876'
lifecycle_stage: active
run_id: f94e47bc97ec4275b31c034cd8e6d079
run_name: stock_model_demo
source_name: ''
source_type: 4
source_version: ''
start_time: 1758301821924
status: 3
tags: []
user_id: Admin
